
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import from environment variables or configuration file
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/services/supabase.config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    // Augmente le timeout pour éviter les problèmes de connexion
    fetch: (url, options) => {
      return fetch(url, {
        ...options,
        headers: {
          ...options?.headers,
          // Ajout d'en-têtes pour améliorer la performance et éviter le cache
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache'
        },
        // Augmentation du timeout pour les requêtes
        signal: options?.signal || (new AbortController().signal)
      });
    }
  }
});
