name: Skip deploy for Lovable

on:
  push:
    branches:
      - main

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy
        run: echo "✅ No deployment needed for this repo"
